In [335]:
import geopandas as gpd
import pandas as pd
from datetime import date

In [357]:
ADMIN2_SHP = 'Data/ET_Admin2_2014/ET_Admin2_2014.shp' #"Data/ET_Admin2_OCHA_2019/eth_admbnda_adm2_csa_bofed_20190827.shp"#
dfad = gpd.read_file(ADMIN2_SHP)
dfad.head()

FNID  EFF_YEAR COUNTRY    ADMIN0  ADMIN1 ADMIN1FR ADMIN1SP  \
0  ET2014A20722      2014      ET  Ethiopia   SNNPR     None     None   
1  ET2014A20411      2014      ET  Ethiopia  Oromia     None     None   
2  ET2014A20708      2014      ET  Ethiopia   SNNPR     None     None   
3  ET2014A20412      2014      ET  Ethiopia  Oromia     None     None   
4  ET2014A20704      2014      ET  Ethiopia   SNNPR     None     None   

  ADMIN1PT  ADMIN2 ADMIN2FR ADMIN2SP ADMIN2PT ALIASES  \
0     None   Segen     None     None     None    None   
1     None    Bale     None     None     None    None   
2     None   Sheka     None     None     None    None   
3     None  Borena     None     None     None    None   
4     None  Sidama     None     None     None    None   

                                            geometry  
0  POLYGON ((37.00893 5.20392, 37.00860 5.21044, ...  
1  POLYGON ((41.52576 7.95226, 41.52766 7.94139, ...  
2  POLYGON ((35.60882 7.81575, 35.60975 7.81142, ...  
3  POLYGON ((37.91887 6.58472, 37.92165 6.57858, ...  
4  POLYGON ((39.12953 6.33941, 39.12851 6.32545, ...

In [379]:
dfad.rename(columns={"ADMIN0":"ADM0_EN","ADMIN1":"ADM1_EN","ADMIN2":"ADM2_EN"},inplace=True)

In [380]:
dfad[dfad.ADM2_EN=="North Shewa"]

FNID  EFF_YEAR COUNTRY   ADM0_EN ADM1_EN ADMIN1FR ADMIN1SP  \
34  ET2014A20305      2014      ET  Ethiopia  Amhara     None     None   
76  ET2014A20406      2014      ET  Ethiopia  Oromia     None     None   

   ADMIN1PT      ADM2_EN ADMIN2FR ADMIN2SP ADMIN2PT  \
34     None  North Shewa     None     None     None   
76     None  North Shewa     None     None     None   

                                  ALIASES  \
34  ~Semien Shewa~North Shoa~Semien Shoa~   
76  ~Semen Shewa~Semien Shewa~North Shoa~   

                                             geometry  
34  POLYGON ((39.69846 10.74737, 39.69724 10.74584...  
76  POLYGON ((38.84808 10.36458, 38.84691 10.36019...

In [381]:
len(dfad.ADM2_EN.unique())

76

In [382]:
dfad.ADM1_EN.unique()

array(['SNNPR', 'Oromia', 'Somali', 'Amhara', 'Tigray', 'Dire Dawa',
       'Harari', 'Gambela', 'Afar', 'Benshangul Gumuz', 'Addis Ababa'],
      dtype=object)

In [383]:
status="CS"
dffn = gpd.read_file("Data/EA_FewsNet/FewsNetRaw/east-africa201910/EA_201910_{}.shp".format(status))

In [384]:
dffn

CS  HA0    _count          _sum       _mean  _count_1        _sum_1  \
0  99.0  0.0       NaN           NaN         NaN       NaN           NaN   
1   1.0  0.0  465616.0  6.287675e+07  135.039927  465616.0  6.287675e+07   
2   1.0  1.0       NaN           NaN         NaN       NaN           NaN   
3   2.0  0.0  322415.0  3.006522e+07   93.250051  322415.0  3.006522e+07   
4   2.0  1.0     471.0  1.748007e+04   37.112675     471.0  1.748007e+04   
5   2.0  2.0       NaN           NaN         NaN       NaN           NaN   
6   3.0  0.0  539451.0  1.897115e+07   35.167504  539451.0  1.897115e+07   
7   3.0  1.0      46.0  1.172878e+03   25.497339      46.0  1.172878e+03   
8   4.0  0.0      63.0  2.236509e+03   35.500146      63.0  2.236509e+03   
9  88.0  0.0       0.0  0.000000e+00         NaN       0.0  0.000000e+00   

      _mean_1                                           geometry  
0         NaN  POLYGON ((45.38624 2.14509, 45.37297 2.12773, ...  
1  135.039927  MULTIPOLYGON (((39.63971 -4.06117, 39.63985 -4...  
2         NaN  MULTIPOLYGON (((23.25022 11.37219, 23.21659 11...  
3   93.250051  MULTIPOLYGON (((39.36784 -4.65351, 39.36945 -4...  
4   37.112675  MULTIPOLYGON (((48.53627 5.34514, 48.53669 5.3...  
5         NaN  POLYGON ((22.58643 12.05581, 22.57712 12.05160...  
6   35.167504  MULTIPOLYGON (((40.78653 -2.33021, 40.78736 -2...  
7   25.497339  MULTIPOLYGON (((33.66052 4.85207, 33.63518 4.7...  
8   35.500146  MULTIPOLYGON (((44.54234 3.74918, 44.57135 3.7...  
9         NaN  MULTIPOLYGON (((29.67210 -0.88200, 29.67230 -0...

In [385]:
overlap = gpd.overlay(dfad, dffn, how='intersection')

In [386]:
overlap.head()

FNID  EFF_YEAR COUNTRY   ADM0_EN ADM1_EN ADMIN1FR ADMIN1SP  \
0  ET2014A20722      2014      ET  Ethiopia   SNNPR     None     None   
1  ET2014A20411      2014      ET  Ethiopia  Oromia     None     None   
2  ET2014A20708      2014      ET  Ethiopia   SNNPR     None     None   
3  ET2014A20412      2014      ET  Ethiopia  Oromia     None     None   
4  ET2014A20704      2014      ET  Ethiopia   SNNPR     None     None   

  ADMIN1PT ADM2_EN ADMIN2FR  ... ALIASES   CS  HA0    _count          _sum  \
0     None   Segen     None  ...    None  1.0  0.0  465616.0  6.287675e+07   
1     None    Bale     None  ...    None  1.0  0.0  465616.0  6.287675e+07   
2     None   Sheka     None  ...    None  1.0  0.0  465616.0  6.287675e+07   
3     None  Borena     None  ...    None  1.0  0.0  465616.0  6.287675e+07   
4     None  Sidama     None  ...    None  1.0  0.0  465616.0  6.287675e+07   

        _mean  _count_1        _sum_1     _mean_1  \
0  135.039927  465616.0  6.287675e+07  135.039927   
1  135.039927  465616.0  6.287675e+07  135.039927   
2  135.039927  465616.0  6.287675e+07  135.039927   
3  135.039927  465616.0  6.287675e+07  135.039927   
4  135.039927  465616.0  6.287675e+07  135.039927   

                                            geometry  
0  POLYGON ((37.55208 5.58759, 37.55528 5.58626, ...  
1  MULTIPOLYGON (((41.08496 6.69672, 41.07436 6.6...  
2  POLYGON ((35.60882 7.81575, 35.60975 7.81142, ...  
3  MULTIPOLYGON (((38.29581 6.42804, 38.29985 6.4...  
4  MULTIPOLYGON (((39.12953 6.33941, 39.12851 6.3...  

[5 rows x 22 columns]

In [387]:
overlap[status].unique()

array([1., 2., 3., 4.])

In [388]:
overlap.shape

(195, 22)

In [389]:
dfad.shape

(77, 14)

In [390]:
overlap[overlap.ADM2_EN=="North Shewa"]

FNID  EFF_YEAR COUNTRY   ADM0_EN ADM1_EN ADMIN1FR ADMIN1SP  \
32   ET2014A20305      2014      ET  Ethiopia  Amhara     None     None   
69   ET2014A20406      2014      ET  Ethiopia  Oromia     None     None   
96   ET2014A20305      2014      ET  Ethiopia  Amhara     None     None   
127  ET2014A20406      2014      ET  Ethiopia  Oromia     None     None   
150  ET2014A20305      2014      ET  Ethiopia  Amhara     None     None   

    ADMIN1PT      ADM2_EN ADMIN2FR  ...  \
32      None  North Shewa     None  ...   
69      None  North Shewa     None  ...   
96      None  North Shewa     None  ...   
127     None  North Shewa     None  ...   
150     None  North Shewa     None  ...   

                                   ALIASES   CS  HA0    _count          _sum  \
32   ~Semien Shewa~North Shoa~Semien Shoa~  1.0  0.0  465616.0  6.287675e+07   
69   ~Semen Shewa~Semien Shewa~North Shoa~  1.0  0.0  465616.0  6.287675e+07   
96   ~Semien Shewa~North Shoa~Semien Shoa~  2.0  0.0  322415.0  3.006522e+07   
127  ~Semen Shewa~Semien Shewa~North Shoa~  2.0  0.0  322415.0  3.006522e+07   
150  ~Semien Shewa~North Shoa~Semien Shoa~  3.0  0.0  539451.0  1.897115e+07   

          _mean  _count_1        _sum_1     _mean_1  \
32   135.039927  465616.0  6.287675e+07  135.039927   
69   135.039927  465616.0  6.287675e+07  135.039927   
96    93.250051  322415.0  3.006522e+07   93.250051   
127   93.250051  322415.0  3.006522e+07   93.250051   
150   35.167504  539451.0  1.897115e+07   35.167504   

                                              geometry  
32   MULTIPOLYGON (((39.98136 10.10599, 39.98226 10...  
69   MULTIPOLYGON (((38.66229 10.05864, 38.66159 10...  
96   MULTIPOLYGON (((39.93145 10.00949, 39.94860 9....  
127  MULTIPOLYGON (((38.84808 10.36458, 38.84737 10...  
150  MULTIPOLYGON (((39.80841 9.13551, 39.80579 9.1...  

[5 rows x 22 columns]

In [391]:
overlap.groupby(["ADM2_EN","ADM1_EN"]).count()

FNID  EFF_YEAR  COUNTRY  ADM0_EN  ADMIN1FR  ADMIN1SP  \
ADM2_EN      ADM1_EN                                                         
Afder        Somali      3         3        3        3         0         0   
Agniwak      Gambela     3         3        3        3         0         0   
Alaba        SNNPR       3         3        3        3         0         0   
Argoba       Amhara      2         2        2        2         0         0   
Arsi         Oromia      3         3        3        3         0         0   
...                    ...       ...      ...      ...       ...       ...   
West Shewa   Oromia      2         2        2        2         0         0   
West Tigray  Tigray      3         3        3        3         0         0   
West Wellega Oromia      3         3        3        3         0         0   
Wolayita     SNNPR       3         3        3        3         0         0   
Yem          SNNPR       1         1        1        1         0         0   

                      ADMIN1PT  ADMIN2FR  ADMIN2SP  ADMIN2PT  ALIASES  CS  \
ADM2_EN      ADM1_EN                                                        
Afder        Somali          0         0         0         0        3   3   
Agniwak      Gambela         0         0         0         0        3   3   
Alaba        SNNPR           0         0         0         0        3   3   
Argoba       Amhara          0         0         0         0        2   2   
Arsi         Oromia          0         0         0         0        3   3   
...                        ...       ...       ...       ...      ...  ..   
West Shewa   Oromia          0         0         0         0        2   2   
West Tigray  Tigray          0         0         0         0        3   3   
West Wellega Oromia          0         0         0         0        3   3   
Wolayita     SNNPR           0         0         0         0        3   3   
Yem          SNNPR           0         0         0         0        1   1   

                      HA0  _count  _sum  _mean  _count_1  _sum_1  _mean_1  \
ADM2_EN      ADM1_EN                                                        
Afder        Somali     3       3     3      3         3       3        3   
Agniwak      Gambela    3       3     3      3         3       3        3   
Alaba        SNNPR      3       3     3      3         3       3        3   
Argoba       Amhara     2       2     2      2         2       2        2   
Arsi         Oromia     3       3     3      3         3       3        3   
...                   ...     ...   ...    ...       ...     ...      ...   
West Shewa   Oromia     2       2     2      2         2       2        2   
West Tigray  Tigray     3       3     3      3         3       3        3   
West Wellega Oromia     3       3     3      3         3       3        3   
Wolayita     SNNPR      3       3     3      3         3       3        3   
Yem          SNNPR      1       1     1      1         1       1        1   

                      geometry  
ADM2_EN      ADM1_EN            
Afder        Somali          3  
Agniwak      Gambela         3  
Alaba        SNNPR           3  
Argoba       Amhara          2  
Arsi         Oromia          3  
...                        ...  
West Shewa   Oromia          2  
West Tigray  Tigray          3  
West Wellega Oromia          3  
Wolayita     SNNPR           3  
Yem          SNNPR           1  

[77 rows x 20 columns]

In [392]:
ad_columns=["ADM0_EN","ADM1_EN","ADM2_EN"]

In [393]:
# overlap.crs

In [394]:
overlap.drop_duplicates().shape

(195, 22)

In [395]:
overlap = overlap.drop_duplicates()
#what is best projection?? Albert cone Africa (102022) not found. 3395 is mercator
overlap['area'] = overlap['geometry'].to_crs("EPSG:3395").area
columns = ad_columns+['geometry', 'area',status]
overlap = overlap[columns]

In [396]:
overlap.head()

ADM0_EN ADM1_EN ADM2_EN  \
0  Ethiopia   SNNPR   Segen   
1  Ethiopia  Oromia    Bale   
2  Ethiopia   SNNPR   Sheka   
3  Ethiopia  Oromia  Borena   
4  Ethiopia   SNNPR  Sidama   

                                            geometry          area   CS  
0  POLYGON ((37.55208 5.58759, 37.55528 5.58626, ...  3.917919e+06  1.0  
1  MULTIPOLYGON (((41.08496 6.69672, 41.07436 6.6...  9.643297e+09  1.0  
2  POLYGON ((35.60882 7.81575, 35.60975 7.81142, ...  2.384086e+09  1.0  
3  MULTIPOLYGON (((38.29581 6.42804, 38.29985 6.4...  3.455112e+07  1.0  
4  MULTIPOLYGON (((39.12953 6.33941, 39.12851 6.3...  3.461145e+09  1.0

In [397]:
overlap.shape

(195, 6)

In [401]:
b=overlap.groupby(["ADM1_EN","ADM2_EN","CS"],as_index=False).sum()

In [398]:
overlap[overlap.ADM1_EN=="Gambela"]

ADM0_EN  ADM1_EN    ADM2_EN  \
31   Ethiopia  Gambela  Mezhenger   
34   Ethiopia  Gambela       Nuer   
55   Ethiopia  Gambela      Itang   
58   Ethiopia  Gambela    Agniwak   
116  Ethiopia  Gambela      Itang   
117  Ethiopia  Gambela    Agniwak   
152  Ethiopia  Gambela       Nuer   
169  Ethiopia  Gambela    Agniwak   
187  Ethiopia  Gambela       Nuer   
188  Ethiopia  Gambela      Itang   

                                              geometry          area   CS  
31   POLYGON ((35.38368 7.12677, 35.37457 7.12057, ...  5.986019e+08  1.0  
34   POLYGON ((34.04939 8.50940, 34.07276 8.48184, ...  4.889847e+09  1.0  
55   MULTIPOLYGON (((34.35097 8.37852, 34.35820 8.3...  2.226456e+09  1.0  
58   POLYGON ((34.96721 8.25042, 35.02067 8.22271, ...  2.364740e+10  1.0  
116  POLYGON ((34.35060 8.38018, 34.35097 8.37852, ...  1.227963e+07  2.0  
117  MULTIPOLYGON (((34.35097 8.37852, 34.35060 8.3...  1.390053e+07  2.0  
152  MULTIPOLYGON (((33.61971 8.46584, 33.62138 8.4...  2.517587e+00  3.0  
169  MULTIPOLYGON (((35.01419 6.42755, 35.01957 6.4...  4.539633e+00  3.0  
187  MULTIPOLYGON (((34.04674 8.52024, 34.04681 8.5...  1.051958e+01  4.0  
188  MULTIPOLYGON (((34.14346 8.65344, 34.14347 8.6...  7.035337e-02  4.0

In [276]:
def return_max_csa(admin1,admin2, df,status,adm2_col="ADM2_EN",adm1_col="ADM1_EN",adm0_col="ADM0_EN"):
    '''
    Return the maximum IPC value in an admin2 district.
    '''
    sub = df.loc[(df[adm1_col]==admin1)&(df[adm2_col]==admin2)]
    mx = sub['area'].max()
    row = sub[[adm0_col,adm1_col,adm2_col,status]].loc[sub['area']==mx]
    return row

In [313]:
def return_max_cs(admin1,admin2, df,status,adm2_col="ADM2_EN",adm1_col="ADM1_EN",adm0_col="ADM0_EN"):
    '''
    Return the maximum IPC value in an admin2 district.
    '''
    sub = df.loc[(df[adm1_col]==admin1)&(df[adm2_col]==admin2)]
    mx = sub['CS'].max()
    
    if np.isnan(mx):
        print(admin1)
        print(sub[status])
        print(sub[[adm0_col,adm1_col,adm2_col,status]])#.loc[sub['CS']==mx])
    row = sub[[adm0_col,adm1_col,adm2_col,status]].loc[sub['CS']==mx].iloc[0]
    return row

In [293]:
# for index, row in overlap[['ADM1_EN',"ADM2_EN"]].drop_duplicates().iterrows():
#     print(row.ADM1_EN)

In [294]:
import numpy as np

In [316]:
overlap2=overlap.copy()

In [317]:
overlap.columns

Index(['ADM0_EN', 'ADM1_EN', 'ADM2_EN', 'geometry', 'area', 'CS'], dtype='object')

In [318]:
overlap2.loc[overlap2[status]>=5,status]=0

In [319]:
# overlap2[overlap2[status]>=5,status]=np.nan

In [320]:
overlap.CS.unique()

array([ 2,  3,  1,  4, 99])

In [321]:
overlap2.CS.unique()

array([2, 3, 1, 4, 0])

In [322]:
overlap2[overlap2.ADM1_EN=="Dire Dawa"]

ADM0_EN    ADM1_EN          ADM2_EN  \
15   Ethiopia  Dire Dawa  Dire Dawa rural   
91   Ethiopia  Dire Dawa  Dire Dawa rural   
209  Ethiopia  Dire Dawa  Dire Dawa rural   
210  Ethiopia  Dire Dawa  Dire Dawa urban   

                                              geometry          area  CS  
15   POLYGON ((41.73354 9.47435, 41.72803 9.48903, ...  5.881837e+06   2  
91   MULTIPOLYGON (((42.33846 9.72070, 42.33977 9.7...  2.589282e+07   3  
209  POLYGON ((42.26265 9.65690, 42.26180 9.65578, ...  9.716578e+08   0  
210  POLYGON ((41.86204 9.67819, 41.87342 9.63059, ...  7.986439e+07   0

In [323]:
overlap2.groupby(["ADM1_EN","ADM2_EN"])["CS"].unique()["Dire Dawa"]

ADM2_EN
Dire Dawa rural    [2, 3, 0]
Dire Dawa urban          [0]
Name: CS, dtype: object

In [324]:
overlap.ADM1_EN.unique()

array(['Somali', 'Gambela', 'SNNP', 'Oromia', 'Benishangul Gumz',
       'Tigray', 'Dire Dawa', 'Amhara', 'Afar', 'Harari', 'Addis Ababa'],
      dtype=object)

In [325]:
overlap2.ADM1_EN.unique()

array(['Somali', 'Gambela', 'SNNP', 'Oromia', 'Benishangul Gumz',
       'Tigray', 'Dire Dawa', 'Amhara', 'Afar', 'Harari', 'Addis Ababa'],
      dtype=object)

In [326]:
new_df = pd.DataFrame(columns=ad_columns+[status])
for index,ad_com in overlap[['ADM1_EN',"ADM2_EN"]].drop_duplicates().iterrows():
    row = return_max_csa(ad_com["ADM1_EN"],ad_com["ADM2_EN"], overlap,status)
    new_df = new_df.append(row)
#     new_df.to_csv(COUNTRY + '_admin2_fewsnet_' + STATUS + str(today) + '.csv')

In [333]:
new_df2 = pd.DataFrame(columns=ad_columns+[status])
for index,ad_com in overlap2[['ADM1_EN',"ADM2_EN"]].drop_duplicates().iterrows():
    row = return_max_cs(ad_com["ADM1_EN"],ad_com["ADM2_EN"], overlap2,status)
    new_df2 = new_df2.append(row)
#     new_df.to_csv(COUNTRY + '_admin2_fewsnet_' + STATUS + str(today) + '.csv')

In [328]:
new_df2.replace(0,np.nan,inplace=True)

In [334]:
new_df2.CS.value_counts()

3    67
2    16
1     4
4     3
0     1
Name: CS, dtype: int64

In [194]:
# new_df = pd.DataFrame(columns=ad_columns+[status])
# for a in overlap['ADM2_EN'].unique():
#     row = return_max_cs(a, overlap,status)
#     new_df = new_df.append(row)
# #     new_df.to_csv(COUNTRY + '_admin2_fewsnet_' + STATUS + str(today) + '.csv')

In [195]:
overlap[overlap.ADM1_EN=="Addis Ababa"]

ADM0_EN      ADM1_EN    ADM2_EN  \
183  Ethiopia  Addis Ababa  Region 14   

                                              geometry          area   CS  
183  POLYGON ((38.78084 9.09042, 38.79131 9.07768, ...  5.530140e+08  1.0

In [196]:
new_df[new_df.ADM1_EN=="Addis Ababa"]

ADM0_EN      ADM1_EN    ADM2_EN   CS
183  Ethiopia  Addis Ababa  Region 14  1.0

In [197]:
new_df2[new_df2.ADM1_EN=="Addis Ababa"]

ADM0_EN      ADM1_EN    ADM2_EN   CS
183  Ethiopia  Addis Ababa  Region 14  1.0

In [198]:
new_df.CS.unique()

array([2., 1., 3.])

In [199]:
new_df2.CS.unique()

array([3., 2., 4., 1.])

In [200]:
new_df2.shape

(91, 4)

In [201]:
new_df.shape

(91, 4)

In [202]:
new_df

ADM0_EN      ADM1_EN       ADM2_EN   CS
0    Ethiopia       Somali         Afder  2.0
1    Ethiopia         SNNP          Alle  2.0
130  Ethiopia       Oromia          Arsi  1.0
71   Ethiopia       Oromia          Bale  3.0
134  Ethiopia         SNNP       Basketo  1.0
..        ...          ...           ...  ...
183  Ethiopia  Addis Ababa     Region 14  1.0
185  Ethiopia         SNNP         Sheka  1.0
197  Ethiopia       Amhara    West Gojam  1.0
201  Ethiopia       Oromia    West Shewa  1.0
202  Ethiopia       Oromia  West Wellega  1.0

[91 rows x 4 columns]